### ISSUE TITLE
Agnostic crypto backend

### ISSUE THREAD

**Issue by trevor-crypto** [aurora-rs/stellar-base-rs#4]
I would like to use this library but not have to rely on `sodiumoxide` for key generation and signing. 

My proposal is to put `KeyPair` behind a feature flag and keep it as a default feature.
Then create a `Signer` trait that can be implemented by a user of this library. `KeyPair` will implement this trait.

I have to fork and do this regardless, but if someone has an idea or desired implementation strategy, please let me know and I will follow that path so the changes can be merged upstream.

**Comment by fracek** [comment]
That sounds good to me. If you send a PR I will review it and update the crate.
